# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pllefebvre/git/pld-comp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pllefebvre/git/pld-comp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pllefebvre/git/pld-comp/CMakeFiles /home/pllefebvre/git/pld-comp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pllefebvre/git/pld-comp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pld-comp

# Build rule for target.
pld-comp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pld-comp
.PHONY : pld-comp

# fast build rule for target.
pld-comp/fast:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/build
.PHONY : pld-comp/fast

bison.tab.o: bison.tab.cpp.o
.PHONY : bison.tab.o

# target to build an object file
bison.tab.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/bison.tab.cpp.o
.PHONY : bison.tab.cpp.o

bison.tab.i: bison.tab.cpp.i
.PHONY : bison.tab.i

# target to preprocess a source file
bison.tab.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/bison.tab.cpp.i
.PHONY : bison.tab.cpp.i

bison.tab.s: bison.tab.cpp.s
.PHONY : bison.tab.s

# target to generate assembly for a file
bison.tab.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/bison.tab.cpp.s
.PHONY : bison.tab.cpp.s

lex.yy.o: lex.yy.cpp.o
.PHONY : lex.yy.o

# target to build an object file
lex.yy.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/lex.yy.cpp.o
.PHONY : lex.yy.cpp.o

lex.yy.i: lex.yy.cpp.i
.PHONY : lex.yy.i

# target to preprocess a source file
lex.yy.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/lex.yy.cpp.i
.PHONY : lex.yy.cpp.i

lex.yy.s: lex.yy.cpp.s
.PHONY : lex.yy.s

# target to generate assembly for a file
lex.yy.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/lex.yy.cpp.s
.PHONY : lex.yy.cpp.s

src/IR/basicBlock/BasicBlock.o: src/IR/basicBlock/BasicBlock.cpp.o
.PHONY : src/IR/basicBlock/BasicBlock.o

# target to build an object file
src/IR/basicBlock/BasicBlock.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/basicBlock/BasicBlock.cpp.o
.PHONY : src/IR/basicBlock/BasicBlock.cpp.o

src/IR/basicBlock/BasicBlock.i: src/IR/basicBlock/BasicBlock.cpp.i
.PHONY : src/IR/basicBlock/BasicBlock.i

# target to preprocess a source file
src/IR/basicBlock/BasicBlock.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/basicBlock/BasicBlock.cpp.i
.PHONY : src/IR/basicBlock/BasicBlock.cpp.i

src/IR/basicBlock/BasicBlock.s: src/IR/basicBlock/BasicBlock.cpp.s
.PHONY : src/IR/basicBlock/BasicBlock.s

# target to generate assembly for a file
src/IR/basicBlock/BasicBlock.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/basicBlock/BasicBlock.cpp.s
.PHONY : src/IR/basicBlock/BasicBlock.cpp.s

src/IR/data/AbstractData.o: src/IR/data/AbstractData.cpp.o
.PHONY : src/IR/data/AbstractData.o

# target to build an object file
src/IR/data/AbstractData.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/AbstractData.cpp.o
.PHONY : src/IR/data/AbstractData.cpp.o

src/IR/data/AbstractData.i: src/IR/data/AbstractData.cpp.i
.PHONY : src/IR/data/AbstractData.i

# target to preprocess a source file
src/IR/data/AbstractData.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/AbstractData.cpp.i
.PHONY : src/IR/data/AbstractData.cpp.i

src/IR/data/AbstractData.s: src/IR/data/AbstractData.cpp.s
.PHONY : src/IR/data/AbstractData.s

# target to generate assembly for a file
src/IR/data/AbstractData.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/AbstractData.cpp.s
.PHONY : src/IR/data/AbstractData.cpp.s

src/IR/data/Memory.o: src/IR/data/Memory.cpp.o
.PHONY : src/IR/data/Memory.o

# target to build an object file
src/IR/data/Memory.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/Memory.cpp.o
.PHONY : src/IR/data/Memory.cpp.o

src/IR/data/Memory.i: src/IR/data/Memory.cpp.i
.PHONY : src/IR/data/Memory.i

# target to preprocess a source file
src/IR/data/Memory.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/Memory.cpp.i
.PHONY : src/IR/data/Memory.cpp.i

src/IR/data/Memory.s: src/IR/data/Memory.cpp.s
.PHONY : src/IR/data/Memory.s

# target to generate assembly for a file
src/IR/data/Memory.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/Memory.cpp.s
.PHONY : src/IR/data/Memory.cpp.s

src/IR/data/Register.o: src/IR/data/Register.cpp.o
.PHONY : src/IR/data/Register.o

# target to build an object file
src/IR/data/Register.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/Register.cpp.o
.PHONY : src/IR/data/Register.cpp.o

src/IR/data/Register.i: src/IR/data/Register.cpp.i
.PHONY : src/IR/data/Register.i

# target to preprocess a source file
src/IR/data/Register.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/Register.cpp.i
.PHONY : src/IR/data/Register.cpp.i

src/IR/data/Register.s: src/IR/data/Register.cpp.s
.PHONY : src/IR/data/Register.s

# target to generate assembly for a file
src/IR/data/Register.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/data/Register.cpp.s
.PHONY : src/IR/data/Register.cpp.s

src/IR/instructions/AbstractInstruction.o: src/IR/instructions/AbstractInstruction.cpp.o
.PHONY : src/IR/instructions/AbstractInstruction.o

# target to build an object file
src/IR/instructions/AbstractInstruction.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractInstruction.cpp.o
.PHONY : src/IR/instructions/AbstractInstruction.cpp.o

src/IR/instructions/AbstractInstruction.i: src/IR/instructions/AbstractInstruction.cpp.i
.PHONY : src/IR/instructions/AbstractInstruction.i

# target to preprocess a source file
src/IR/instructions/AbstractInstruction.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractInstruction.cpp.i
.PHONY : src/IR/instructions/AbstractInstruction.cpp.i

src/IR/instructions/AbstractInstruction.s: src/IR/instructions/AbstractInstruction.cpp.s
.PHONY : src/IR/instructions/AbstractInstruction.s

# target to generate assembly for a file
src/IR/instructions/AbstractInstruction.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractInstruction.cpp.s
.PHONY : src/IR/instructions/AbstractInstruction.cpp.s

src/IR/instructions/AbstractMemoryAcess.o: src/IR/instructions/AbstractMemoryAcess.cpp.o
.PHONY : src/IR/instructions/AbstractMemoryAcess.o

# target to build an object file
src/IR/instructions/AbstractMemoryAcess.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractMemoryAcess.cpp.o
.PHONY : src/IR/instructions/AbstractMemoryAcess.cpp.o

src/IR/instructions/AbstractMemoryAcess.i: src/IR/instructions/AbstractMemoryAcess.cpp.i
.PHONY : src/IR/instructions/AbstractMemoryAcess.i

# target to preprocess a source file
src/IR/instructions/AbstractMemoryAcess.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractMemoryAcess.cpp.i
.PHONY : src/IR/instructions/AbstractMemoryAcess.cpp.i

src/IR/instructions/AbstractMemoryAcess.s: src/IR/instructions/AbstractMemoryAcess.cpp.s
.PHONY : src/IR/instructions/AbstractMemoryAcess.s

# target to generate assembly for a file
src/IR/instructions/AbstractMemoryAcess.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractMemoryAcess.cpp.s
.PHONY : src/IR/instructions/AbstractMemoryAcess.cpp.s

src/IR/instructions/AbstractOperator.o: src/IR/instructions/AbstractOperator.cpp.o
.PHONY : src/IR/instructions/AbstractOperator.o

# target to build an object file
src/IR/instructions/AbstractOperator.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractOperator.cpp.o
.PHONY : src/IR/instructions/AbstractOperator.cpp.o

src/IR/instructions/AbstractOperator.i: src/IR/instructions/AbstractOperator.cpp.i
.PHONY : src/IR/instructions/AbstractOperator.i

# target to preprocess a source file
src/IR/instructions/AbstractOperator.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractOperator.cpp.i
.PHONY : src/IR/instructions/AbstractOperator.cpp.i

src/IR/instructions/AbstractOperator.s: src/IR/instructions/AbstractOperator.cpp.s
.PHONY : src/IR/instructions/AbstractOperator.s

# target to generate assembly for a file
src/IR/instructions/AbstractOperator.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/AbstractOperator.cpp.s
.PHONY : src/IR/instructions/AbstractOperator.cpp.s

src/IR/instructions/Jump.o: src/IR/instructions/Jump.cpp.o
.PHONY : src/IR/instructions/Jump.o

# target to build an object file
src/IR/instructions/Jump.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/Jump.cpp.o
.PHONY : src/IR/instructions/Jump.cpp.o

src/IR/instructions/Jump.i: src/IR/instructions/Jump.cpp.i
.PHONY : src/IR/instructions/Jump.i

# target to preprocess a source file
src/IR/instructions/Jump.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/Jump.cpp.i
.PHONY : src/IR/instructions/Jump.cpp.i

src/IR/instructions/Jump.s: src/IR/instructions/Jump.cpp.s
.PHONY : src/IR/instructions/Jump.s

# target to generate assembly for a file
src/IR/instructions/Jump.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/Jump.cpp.s
.PHONY : src/IR/instructions/Jump.cpp.s

src/IR/instructions/Label.o: src/IR/instructions/Label.cpp.o
.PHONY : src/IR/instructions/Label.o

# target to build an object file
src/IR/instructions/Label.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/Label.cpp.o
.PHONY : src/IR/instructions/Label.cpp.o

src/IR/instructions/Label.i: src/IR/instructions/Label.cpp.i
.PHONY : src/IR/instructions/Label.i

# target to preprocess a source file
src/IR/instructions/Label.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/Label.cpp.i
.PHONY : src/IR/instructions/Label.cpp.i

src/IR/instructions/Label.s: src/IR/instructions/Label.cpp.s
.PHONY : src/IR/instructions/Label.s

# target to generate assembly for a file
src/IR/instructions/Label.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/Label.cpp.s
.PHONY : src/IR/instructions/Label.cpp.s

src/IR/instructions/OperatorBigger.o: src/IR/instructions/OperatorBigger.cpp.o
.PHONY : src/IR/instructions/OperatorBigger.o

# target to build an object file
src/IR/instructions/OperatorBigger.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorBigger.cpp.o
.PHONY : src/IR/instructions/OperatorBigger.cpp.o

src/IR/instructions/OperatorBigger.i: src/IR/instructions/OperatorBigger.cpp.i
.PHONY : src/IR/instructions/OperatorBigger.i

# target to preprocess a source file
src/IR/instructions/OperatorBigger.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorBigger.cpp.i
.PHONY : src/IR/instructions/OperatorBigger.cpp.i

src/IR/instructions/OperatorBigger.s: src/IR/instructions/OperatorBigger.cpp.s
.PHONY : src/IR/instructions/OperatorBigger.s

# target to generate assembly for a file
src/IR/instructions/OperatorBigger.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorBigger.cpp.s
.PHONY : src/IR/instructions/OperatorBigger.cpp.s

src/IR/instructions/OperatorBiggerOrEqual.o: src/IR/instructions/OperatorBiggerOrEqual.cpp.o
.PHONY : src/IR/instructions/OperatorBiggerOrEqual.o

# target to build an object file
src/IR/instructions/OperatorBiggerOrEqual.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorBiggerOrEqual.cpp.o
.PHONY : src/IR/instructions/OperatorBiggerOrEqual.cpp.o

src/IR/instructions/OperatorBiggerOrEqual.i: src/IR/instructions/OperatorBiggerOrEqual.cpp.i
.PHONY : src/IR/instructions/OperatorBiggerOrEqual.i

# target to preprocess a source file
src/IR/instructions/OperatorBiggerOrEqual.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorBiggerOrEqual.cpp.i
.PHONY : src/IR/instructions/OperatorBiggerOrEqual.cpp.i

src/IR/instructions/OperatorBiggerOrEqual.s: src/IR/instructions/OperatorBiggerOrEqual.cpp.s
.PHONY : src/IR/instructions/OperatorBiggerOrEqual.s

# target to generate assembly for a file
src/IR/instructions/OperatorBiggerOrEqual.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorBiggerOrEqual.cpp.s
.PHONY : src/IR/instructions/OperatorBiggerOrEqual.cpp.s

src/IR/instructions/OperatorDiv.o: src/IR/instructions/OperatorDiv.cpp.o
.PHONY : src/IR/instructions/OperatorDiv.o

# target to build an object file
src/IR/instructions/OperatorDiv.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorDiv.cpp.o
.PHONY : src/IR/instructions/OperatorDiv.cpp.o

src/IR/instructions/OperatorDiv.i: src/IR/instructions/OperatorDiv.cpp.i
.PHONY : src/IR/instructions/OperatorDiv.i

# target to preprocess a source file
src/IR/instructions/OperatorDiv.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorDiv.cpp.i
.PHONY : src/IR/instructions/OperatorDiv.cpp.i

src/IR/instructions/OperatorDiv.s: src/IR/instructions/OperatorDiv.cpp.s
.PHONY : src/IR/instructions/OperatorDiv.s

# target to generate assembly for a file
src/IR/instructions/OperatorDiv.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorDiv.cpp.s
.PHONY : src/IR/instructions/OperatorDiv.cpp.s

src/IR/instructions/OperatorEquals.o: src/IR/instructions/OperatorEquals.cpp.o
.PHONY : src/IR/instructions/OperatorEquals.o

# target to build an object file
src/IR/instructions/OperatorEquals.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorEquals.cpp.o
.PHONY : src/IR/instructions/OperatorEquals.cpp.o

src/IR/instructions/OperatorEquals.i: src/IR/instructions/OperatorEquals.cpp.i
.PHONY : src/IR/instructions/OperatorEquals.i

# target to preprocess a source file
src/IR/instructions/OperatorEquals.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorEquals.cpp.i
.PHONY : src/IR/instructions/OperatorEquals.cpp.i

src/IR/instructions/OperatorEquals.s: src/IR/instructions/OperatorEquals.cpp.s
.PHONY : src/IR/instructions/OperatorEquals.s

# target to generate assembly for a file
src/IR/instructions/OperatorEquals.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorEquals.cpp.s
.PHONY : src/IR/instructions/OperatorEquals.cpp.s

src/IR/instructions/OperatorMinus.o: src/IR/instructions/OperatorMinus.cpp.o
.PHONY : src/IR/instructions/OperatorMinus.o

# target to build an object file
src/IR/instructions/OperatorMinus.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorMinus.cpp.o
.PHONY : src/IR/instructions/OperatorMinus.cpp.o

src/IR/instructions/OperatorMinus.i: src/IR/instructions/OperatorMinus.cpp.i
.PHONY : src/IR/instructions/OperatorMinus.i

# target to preprocess a source file
src/IR/instructions/OperatorMinus.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorMinus.cpp.i
.PHONY : src/IR/instructions/OperatorMinus.cpp.i

src/IR/instructions/OperatorMinus.s: src/IR/instructions/OperatorMinus.cpp.s
.PHONY : src/IR/instructions/OperatorMinus.s

# target to generate assembly for a file
src/IR/instructions/OperatorMinus.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorMinus.cpp.s
.PHONY : src/IR/instructions/OperatorMinus.cpp.s

src/IR/instructions/OperatorModulus.o: src/IR/instructions/OperatorModulus.cpp.o
.PHONY : src/IR/instructions/OperatorModulus.o

# target to build an object file
src/IR/instructions/OperatorModulus.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorModulus.cpp.o
.PHONY : src/IR/instructions/OperatorModulus.cpp.o

src/IR/instructions/OperatorModulus.i: src/IR/instructions/OperatorModulus.cpp.i
.PHONY : src/IR/instructions/OperatorModulus.i

# target to preprocess a source file
src/IR/instructions/OperatorModulus.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorModulus.cpp.i
.PHONY : src/IR/instructions/OperatorModulus.cpp.i

src/IR/instructions/OperatorModulus.s: src/IR/instructions/OperatorModulus.cpp.s
.PHONY : src/IR/instructions/OperatorModulus.s

# target to generate assembly for a file
src/IR/instructions/OperatorModulus.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorModulus.cpp.s
.PHONY : src/IR/instructions/OperatorModulus.cpp.s

src/IR/instructions/OperatorMult.o: src/IR/instructions/OperatorMult.cpp.o
.PHONY : src/IR/instructions/OperatorMult.o

# target to build an object file
src/IR/instructions/OperatorMult.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorMult.cpp.o
.PHONY : src/IR/instructions/OperatorMult.cpp.o

src/IR/instructions/OperatorMult.i: src/IR/instructions/OperatorMult.cpp.i
.PHONY : src/IR/instructions/OperatorMult.i

# target to preprocess a source file
src/IR/instructions/OperatorMult.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorMult.cpp.i
.PHONY : src/IR/instructions/OperatorMult.cpp.i

src/IR/instructions/OperatorMult.s: src/IR/instructions/OperatorMult.cpp.s
.PHONY : src/IR/instructions/OperatorMult.s

# target to generate assembly for a file
src/IR/instructions/OperatorMult.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorMult.cpp.s
.PHONY : src/IR/instructions/OperatorMult.cpp.s

src/IR/instructions/OperatorPlus.o: src/IR/instructions/OperatorPlus.cpp.o
.PHONY : src/IR/instructions/OperatorPlus.o

# target to build an object file
src/IR/instructions/OperatorPlus.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorPlus.cpp.o
.PHONY : src/IR/instructions/OperatorPlus.cpp.o

src/IR/instructions/OperatorPlus.i: src/IR/instructions/OperatorPlus.cpp.i
.PHONY : src/IR/instructions/OperatorPlus.i

# target to preprocess a source file
src/IR/instructions/OperatorPlus.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorPlus.cpp.i
.PHONY : src/IR/instructions/OperatorPlus.cpp.i

src/IR/instructions/OperatorPlus.s: src/IR/instructions/OperatorPlus.cpp.s
.PHONY : src/IR/instructions/OperatorPlus.s

# target to generate assembly for a file
src/IR/instructions/OperatorPlus.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorPlus.cpp.s
.PHONY : src/IR/instructions/OperatorPlus.cpp.s

src/IR/instructions/OperatorSmaller.o: src/IR/instructions/OperatorSmaller.cpp.o
.PHONY : src/IR/instructions/OperatorSmaller.o

# target to build an object file
src/IR/instructions/OperatorSmaller.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorSmaller.cpp.o
.PHONY : src/IR/instructions/OperatorSmaller.cpp.o

src/IR/instructions/OperatorSmaller.i: src/IR/instructions/OperatorSmaller.cpp.i
.PHONY : src/IR/instructions/OperatorSmaller.i

# target to preprocess a source file
src/IR/instructions/OperatorSmaller.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorSmaller.cpp.i
.PHONY : src/IR/instructions/OperatorSmaller.cpp.i

src/IR/instructions/OperatorSmaller.s: src/IR/instructions/OperatorSmaller.cpp.s
.PHONY : src/IR/instructions/OperatorSmaller.s

# target to generate assembly for a file
src/IR/instructions/OperatorSmaller.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorSmaller.cpp.s
.PHONY : src/IR/instructions/OperatorSmaller.cpp.s

src/IR/instructions/OperatorSmallerOrEqual.o: src/IR/instructions/OperatorSmallerOrEqual.cpp.o
.PHONY : src/IR/instructions/OperatorSmallerOrEqual.o

# target to build an object file
src/IR/instructions/OperatorSmallerOrEqual.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorSmallerOrEqual.cpp.o
.PHONY : src/IR/instructions/OperatorSmallerOrEqual.cpp.o

src/IR/instructions/OperatorSmallerOrEqual.i: src/IR/instructions/OperatorSmallerOrEqual.cpp.i
.PHONY : src/IR/instructions/OperatorSmallerOrEqual.i

# target to preprocess a source file
src/IR/instructions/OperatorSmallerOrEqual.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorSmallerOrEqual.cpp.i
.PHONY : src/IR/instructions/OperatorSmallerOrEqual.cpp.i

src/IR/instructions/OperatorSmallerOrEqual.s: src/IR/instructions/OperatorSmallerOrEqual.cpp.s
.PHONY : src/IR/instructions/OperatorSmallerOrEqual.s

# target to generate assembly for a file
src/IR/instructions/OperatorSmallerOrEqual.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/OperatorSmallerOrEqual.cpp.s
.PHONY : src/IR/instructions/OperatorSmallerOrEqual.cpp.s

src/IR/instructions/ReadFromMemory.o: src/IR/instructions/ReadFromMemory.cpp.o
.PHONY : src/IR/instructions/ReadFromMemory.o

# target to build an object file
src/IR/instructions/ReadFromMemory.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/ReadFromMemory.cpp.o
.PHONY : src/IR/instructions/ReadFromMemory.cpp.o

src/IR/instructions/ReadFromMemory.i: src/IR/instructions/ReadFromMemory.cpp.i
.PHONY : src/IR/instructions/ReadFromMemory.i

# target to preprocess a source file
src/IR/instructions/ReadFromMemory.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/ReadFromMemory.cpp.i
.PHONY : src/IR/instructions/ReadFromMemory.cpp.i

src/IR/instructions/ReadFromMemory.s: src/IR/instructions/ReadFromMemory.cpp.s
.PHONY : src/IR/instructions/ReadFromMemory.s

# target to generate assembly for a file
src/IR/instructions/ReadFromMemory.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/ReadFromMemory.cpp.s
.PHONY : src/IR/instructions/ReadFromMemory.cpp.s

src/IR/instructions/WriteToMemory.o: src/IR/instructions/WriteToMemory.cpp.o
.PHONY : src/IR/instructions/WriteToMemory.o

# target to build an object file
src/IR/instructions/WriteToMemory.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/WriteToMemory.cpp.o
.PHONY : src/IR/instructions/WriteToMemory.cpp.o

src/IR/instructions/WriteToMemory.i: src/IR/instructions/WriteToMemory.cpp.i
.PHONY : src/IR/instructions/WriteToMemory.i

# target to preprocess a source file
src/IR/instructions/WriteToMemory.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/WriteToMemory.cpp.i
.PHONY : src/IR/instructions/WriteToMemory.cpp.i

src/IR/instructions/WriteToMemory.s: src/IR/instructions/WriteToMemory.cpp.s
.PHONY : src/IR/instructions/WriteToMemory.s

# target to generate assembly for a file
src/IR/instructions/WriteToMemory.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/IR/instructions/WriteToMemory.cpp.s
.PHONY : src/IR/instructions/WriteToMemory.cpp.s

src/flex/AST/AbstractInstruction.o: src/flex/AST/AbstractInstruction.cpp.o
.PHONY : src/flex/AST/AbstractInstruction.o

# target to build an object file
src/flex/AST/AbstractInstruction.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AbstractInstruction.cpp.o
.PHONY : src/flex/AST/AbstractInstruction.cpp.o

src/flex/AST/AbstractInstruction.i: src/flex/AST/AbstractInstruction.cpp.i
.PHONY : src/flex/AST/AbstractInstruction.i

# target to preprocess a source file
src/flex/AST/AbstractInstruction.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AbstractInstruction.cpp.i
.PHONY : src/flex/AST/AbstractInstruction.cpp.i

src/flex/AST/AbstractInstruction.s: src/flex/AST/AbstractInstruction.cpp.s
.PHONY : src/flex/AST/AbstractInstruction.s

# target to generate assembly for a file
src/flex/AST/AbstractInstruction.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AbstractInstruction.cpp.s
.PHONY : src/flex/AST/AbstractInstruction.cpp.s

src/flex/AST/AbstractNode.o: src/flex/AST/AbstractNode.cpp.o
.PHONY : src/flex/AST/AbstractNode.o

# target to build an object file
src/flex/AST/AbstractNode.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AbstractNode.cpp.o
.PHONY : src/flex/AST/AbstractNode.cpp.o

src/flex/AST/AbstractNode.i: src/flex/AST/AbstractNode.cpp.i
.PHONY : src/flex/AST/AbstractNode.i

# target to preprocess a source file
src/flex/AST/AbstractNode.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AbstractNode.cpp.i
.PHONY : src/flex/AST/AbstractNode.cpp.i

src/flex/AST/AbstractNode.s: src/flex/AST/AbstractNode.cpp.s
.PHONY : src/flex/AST/AbstractNode.s

# target to generate assembly for a file
src/flex/AST/AbstractNode.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AbstractNode.cpp.s
.PHONY : src/flex/AST/AbstractNode.cpp.s

src/flex/AST/ArgumentList.o: src/flex/AST/ArgumentList.cpp.o
.PHONY : src/flex/AST/ArgumentList.o

# target to build an object file
src/flex/AST/ArgumentList.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/ArgumentList.cpp.o
.PHONY : src/flex/AST/ArgumentList.cpp.o

src/flex/AST/ArgumentList.i: src/flex/AST/ArgumentList.cpp.i
.PHONY : src/flex/AST/ArgumentList.i

# target to preprocess a source file
src/flex/AST/ArgumentList.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/ArgumentList.cpp.i
.PHONY : src/flex/AST/ArgumentList.cpp.i

src/flex/AST/ArgumentList.s: src/flex/AST/ArgumentList.cpp.s
.PHONY : src/flex/AST/ArgumentList.s

# target to generate assembly for a file
src/flex/AST/ArgumentList.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/ArgumentList.cpp.s
.PHONY : src/flex/AST/ArgumentList.cpp.s

src/flex/AST/AssignationVariableExpression.o: src/flex/AST/AssignationVariableExpression.cpp.o
.PHONY : src/flex/AST/AssignationVariableExpression.o

# target to build an object file
src/flex/AST/AssignationVariableExpression.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AssignationVariableExpression.cpp.o
.PHONY : src/flex/AST/AssignationVariableExpression.cpp.o

src/flex/AST/AssignationVariableExpression.i: src/flex/AST/AssignationVariableExpression.cpp.i
.PHONY : src/flex/AST/AssignationVariableExpression.i

# target to preprocess a source file
src/flex/AST/AssignationVariableExpression.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AssignationVariableExpression.cpp.i
.PHONY : src/flex/AST/AssignationVariableExpression.cpp.i

src/flex/AST/AssignationVariableExpression.s: src/flex/AST/AssignationVariableExpression.cpp.s
.PHONY : src/flex/AST/AssignationVariableExpression.s

# target to generate assembly for a file
src/flex/AST/AssignationVariableExpression.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/AssignationVariableExpression.cpp.s
.PHONY : src/flex/AST/AssignationVariableExpression.cpp.s

src/flex/AST/Block.o: src/flex/AST/Block.cpp.o
.PHONY : src/flex/AST/Block.o

# target to build an object file
src/flex/AST/Block.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Block.cpp.o
.PHONY : src/flex/AST/Block.cpp.o

src/flex/AST/Block.i: src/flex/AST/Block.cpp.i
.PHONY : src/flex/AST/Block.i

# target to preprocess a source file
src/flex/AST/Block.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Block.cpp.i
.PHONY : src/flex/AST/Block.cpp.i

src/flex/AST/Block.s: src/flex/AST/Block.cpp.s
.PHONY : src/flex/AST/Block.s

# target to generate assembly for a file
src/flex/AST/Block.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Block.cpp.s
.PHONY : src/flex/AST/Block.cpp.s

src/flex/AST/ComposedInstruction.o: src/flex/AST/ComposedInstruction.cpp.o
.PHONY : src/flex/AST/ComposedInstruction.o

# target to build an object file
src/flex/AST/ComposedInstruction.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/ComposedInstruction.cpp.o
.PHONY : src/flex/AST/ComposedInstruction.cpp.o

src/flex/AST/ComposedInstruction.i: src/flex/AST/ComposedInstruction.cpp.i
.PHONY : src/flex/AST/ComposedInstruction.i

# target to preprocess a source file
src/flex/AST/ComposedInstruction.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/ComposedInstruction.cpp.i
.PHONY : src/flex/AST/ComposedInstruction.cpp.i

src/flex/AST/ComposedInstruction.s: src/flex/AST/ComposedInstruction.cpp.s
.PHONY : src/flex/AST/ComposedInstruction.s

# target to generate assembly for a file
src/flex/AST/ComposedInstruction.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/ComposedInstruction.cpp.s
.PHONY : src/flex/AST/ComposedInstruction.cpp.s

src/flex/AST/Expression/AbstractBinaryExpression.o: src/flex/AST/Expression/AbstractBinaryExpression.cpp.o
.PHONY : src/flex/AST/Expression/AbstractBinaryExpression.o

# target to build an object file
src/flex/AST/Expression/AbstractBinaryExpression.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AbstractBinaryExpression.cpp.o
.PHONY : src/flex/AST/Expression/AbstractBinaryExpression.cpp.o

src/flex/AST/Expression/AbstractBinaryExpression.i: src/flex/AST/Expression/AbstractBinaryExpression.cpp.i
.PHONY : src/flex/AST/Expression/AbstractBinaryExpression.i

# target to preprocess a source file
src/flex/AST/Expression/AbstractBinaryExpression.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AbstractBinaryExpression.cpp.i
.PHONY : src/flex/AST/Expression/AbstractBinaryExpression.cpp.i

src/flex/AST/Expression/AbstractBinaryExpression.s: src/flex/AST/Expression/AbstractBinaryExpression.cpp.s
.PHONY : src/flex/AST/Expression/AbstractBinaryExpression.s

# target to generate assembly for a file
src/flex/AST/Expression/AbstractBinaryExpression.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AbstractBinaryExpression.cpp.s
.PHONY : src/flex/AST/Expression/AbstractBinaryExpression.cpp.s

src/flex/AST/Expression/AbstractExpression.o: src/flex/AST/Expression/AbstractExpression.cpp.o
.PHONY : src/flex/AST/Expression/AbstractExpression.o

# target to build an object file
src/flex/AST/Expression/AbstractExpression.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AbstractExpression.cpp.o
.PHONY : src/flex/AST/Expression/AbstractExpression.cpp.o

src/flex/AST/Expression/AbstractExpression.i: src/flex/AST/Expression/AbstractExpression.cpp.i
.PHONY : src/flex/AST/Expression/AbstractExpression.i

# target to preprocess a source file
src/flex/AST/Expression/AbstractExpression.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AbstractExpression.cpp.i
.PHONY : src/flex/AST/Expression/AbstractExpression.cpp.i

src/flex/AST/Expression/AbstractExpression.s: src/flex/AST/Expression/AbstractExpression.cpp.s
.PHONY : src/flex/AST/Expression/AbstractExpression.s

# target to generate assembly for a file
src/flex/AST/Expression/AbstractExpression.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AbstractExpression.cpp.s
.PHONY : src/flex/AST/Expression/AbstractExpression.cpp.s

src/flex/AST/Expression/AddExpression.o: src/flex/AST/Expression/AddExpression.cpp.o
.PHONY : src/flex/AST/Expression/AddExpression.o

# target to build an object file
src/flex/AST/Expression/AddExpression.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AddExpression.cpp.o
.PHONY : src/flex/AST/Expression/AddExpression.cpp.o

src/flex/AST/Expression/AddExpression.i: src/flex/AST/Expression/AddExpression.cpp.i
.PHONY : src/flex/AST/Expression/AddExpression.i

# target to preprocess a source file
src/flex/AST/Expression/AddExpression.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AddExpression.cpp.i
.PHONY : src/flex/AST/Expression/AddExpression.cpp.i

src/flex/AST/Expression/AddExpression.s: src/flex/AST/Expression/AddExpression.cpp.s
.PHONY : src/flex/AST/Expression/AddExpression.s

# target to generate assembly for a file
src/flex/AST/Expression/AddExpression.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/AddExpression.cpp.s
.PHONY : src/flex/AST/Expression/AddExpression.cpp.s

src/flex/AST/Expression/Constant.o: src/flex/AST/Expression/Constant.cpp.o
.PHONY : src/flex/AST/Expression/Constant.o

# target to build an object file
src/flex/AST/Expression/Constant.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/Constant.cpp.o
.PHONY : src/flex/AST/Expression/Constant.cpp.o

src/flex/AST/Expression/Constant.i: src/flex/AST/Expression/Constant.cpp.i
.PHONY : src/flex/AST/Expression/Constant.i

# target to preprocess a source file
src/flex/AST/Expression/Constant.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/Constant.cpp.i
.PHONY : src/flex/AST/Expression/Constant.cpp.i

src/flex/AST/Expression/Constant.s: src/flex/AST/Expression/Constant.cpp.s
.PHONY : src/flex/AST/Expression/Constant.s

# target to generate assembly for a file
src/flex/AST/Expression/Constant.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/Constant.cpp.s
.PHONY : src/flex/AST/Expression/Constant.cpp.s

src/flex/AST/Expression/VariableAssignmentExpression.o: src/flex/AST/Expression/VariableAssignmentExpression.cpp.o
.PHONY : src/flex/AST/Expression/VariableAssignmentExpression.o

# target to build an object file
src/flex/AST/Expression/VariableAssignmentExpression.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/VariableAssignmentExpression.cpp.o
.PHONY : src/flex/AST/Expression/VariableAssignmentExpression.cpp.o

src/flex/AST/Expression/VariableAssignmentExpression.i: src/flex/AST/Expression/VariableAssignmentExpression.cpp.i
.PHONY : src/flex/AST/Expression/VariableAssignmentExpression.i

# target to preprocess a source file
src/flex/AST/Expression/VariableAssignmentExpression.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/VariableAssignmentExpression.cpp.i
.PHONY : src/flex/AST/Expression/VariableAssignmentExpression.cpp.i

src/flex/AST/Expression/VariableAssignmentExpression.s: src/flex/AST/Expression/VariableAssignmentExpression.cpp.s
.PHONY : src/flex/AST/Expression/VariableAssignmentExpression.s

# target to generate assembly for a file
src/flex/AST/Expression/VariableAssignmentExpression.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Expression/VariableAssignmentExpression.cpp.s
.PHONY : src/flex/AST/Expression/VariableAssignmentExpression.cpp.s

src/flex/AST/MainBody.o: src/flex/AST/MainBody.cpp.o
.PHONY : src/flex/AST/MainBody.o

# target to build an object file
src/flex/AST/MainBody.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/MainBody.cpp.o
.PHONY : src/flex/AST/MainBody.cpp.o

src/flex/AST/MainBody.i: src/flex/AST/MainBody.cpp.i
.PHONY : src/flex/AST/MainBody.i

# target to preprocess a source file
src/flex/AST/MainBody.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/MainBody.cpp.i
.PHONY : src/flex/AST/MainBody.cpp.i

src/flex/AST/MainBody.s: src/flex/AST/MainBody.cpp.s
.PHONY : src/flex/AST/MainBody.s

# target to generate assembly for a file
src/flex/AST/MainBody.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/MainBody.cpp.s
.PHONY : src/flex/AST/MainBody.cpp.s

src/flex/AST/MainType.o: src/flex/AST/MainType.cpp.o
.PHONY : src/flex/AST/MainType.o

# target to build an object file
src/flex/AST/MainType.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/MainType.cpp.o
.PHONY : src/flex/AST/MainType.cpp.o

src/flex/AST/MainType.i: src/flex/AST/MainType.cpp.i
.PHONY : src/flex/AST/MainType.i

# target to preprocess a source file
src/flex/AST/MainType.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/MainType.cpp.i
.PHONY : src/flex/AST/MainType.cpp.i

src/flex/AST/MainType.s: src/flex/AST/MainType.cpp.s
.PHONY : src/flex/AST/MainType.s

# target to generate assembly for a file
src/flex/AST/MainType.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/MainType.cpp.s
.PHONY : src/flex/AST/MainType.cpp.s

src/flex/AST/SequenceInstruction.o: src/flex/AST/SequenceInstruction.cpp.o
.PHONY : src/flex/AST/SequenceInstruction.o

# target to build an object file
src/flex/AST/SequenceInstruction.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/SequenceInstruction.cpp.o
.PHONY : src/flex/AST/SequenceInstruction.cpp.o

src/flex/AST/SequenceInstruction.i: src/flex/AST/SequenceInstruction.cpp.i
.PHONY : src/flex/AST/SequenceInstruction.i

# target to preprocess a source file
src/flex/AST/SequenceInstruction.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/SequenceInstruction.cpp.i
.PHONY : src/flex/AST/SequenceInstruction.cpp.i

src/flex/AST/SequenceInstruction.s: src/flex/AST/SequenceInstruction.cpp.s
.PHONY : src/flex/AST/SequenceInstruction.s

# target to generate assembly for a file
src/flex/AST/SequenceInstruction.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/SequenceInstruction.cpp.s
.PHONY : src/flex/AST/SequenceInstruction.cpp.s

src/flex/AST/Structure/AbstractStructure.o: src/flex/AST/Structure/AbstractStructure.cpp.o
.PHONY : src/flex/AST/Structure/AbstractStructure.o

# target to build an object file
src/flex/AST/Structure/AbstractStructure.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/AbstractStructure.cpp.o
.PHONY : src/flex/AST/Structure/AbstractStructure.cpp.o

src/flex/AST/Structure/AbstractStructure.i: src/flex/AST/Structure/AbstractStructure.cpp.i
.PHONY : src/flex/AST/Structure/AbstractStructure.i

# target to preprocess a source file
src/flex/AST/Structure/AbstractStructure.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/AbstractStructure.cpp.i
.PHONY : src/flex/AST/Structure/AbstractStructure.cpp.i

src/flex/AST/Structure/AbstractStructure.s: src/flex/AST/Structure/AbstractStructure.cpp.s
.PHONY : src/flex/AST/Structure/AbstractStructure.s

# target to generate assembly for a file
src/flex/AST/Structure/AbstractStructure.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/AbstractStructure.cpp.s
.PHONY : src/flex/AST/Structure/AbstractStructure.cpp.s

src/flex/AST/Structure/ElseStructure.o: src/flex/AST/Structure/ElseStructure.cpp.o
.PHONY : src/flex/AST/Structure/ElseStructure.o

# target to build an object file
src/flex/AST/Structure/ElseStructure.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/ElseStructure.cpp.o
.PHONY : src/flex/AST/Structure/ElseStructure.cpp.o

src/flex/AST/Structure/ElseStructure.i: src/flex/AST/Structure/ElseStructure.cpp.i
.PHONY : src/flex/AST/Structure/ElseStructure.i

# target to preprocess a source file
src/flex/AST/Structure/ElseStructure.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/ElseStructure.cpp.i
.PHONY : src/flex/AST/Structure/ElseStructure.cpp.i

src/flex/AST/Structure/ElseStructure.s: src/flex/AST/Structure/ElseStructure.cpp.s
.PHONY : src/flex/AST/Structure/ElseStructure.s

# target to generate assembly for a file
src/flex/AST/Structure/ElseStructure.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/ElseStructure.cpp.s
.PHONY : src/flex/AST/Structure/ElseStructure.cpp.s

src/flex/AST/Structure/IfStructure.o: src/flex/AST/Structure/IfStructure.cpp.o
.PHONY : src/flex/AST/Structure/IfStructure.o

# target to build an object file
src/flex/AST/Structure/IfStructure.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/IfStructure.cpp.o
.PHONY : src/flex/AST/Structure/IfStructure.cpp.o

src/flex/AST/Structure/IfStructure.i: src/flex/AST/Structure/IfStructure.cpp.i
.PHONY : src/flex/AST/Structure/IfStructure.i

# target to preprocess a source file
src/flex/AST/Structure/IfStructure.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/IfStructure.cpp.i
.PHONY : src/flex/AST/Structure/IfStructure.cpp.i

src/flex/AST/Structure/IfStructure.s: src/flex/AST/Structure/IfStructure.cpp.s
.PHONY : src/flex/AST/Structure/IfStructure.s

# target to generate assembly for a file
src/flex/AST/Structure/IfStructure.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Structure/IfStructure.cpp.s
.PHONY : src/flex/AST/Structure/IfStructure.cpp.s

src/flex/AST/UnitInstruction.o: src/flex/AST/UnitInstruction.cpp.o
.PHONY : src/flex/AST/UnitInstruction.o

# target to build an object file
src/flex/AST/UnitInstruction.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/UnitInstruction.cpp.o
.PHONY : src/flex/AST/UnitInstruction.cpp.o

src/flex/AST/UnitInstruction.i: src/flex/AST/UnitInstruction.cpp.i
.PHONY : src/flex/AST/UnitInstruction.i

# target to preprocess a source file
src/flex/AST/UnitInstruction.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/UnitInstruction.cpp.i
.PHONY : src/flex/AST/UnitInstruction.cpp.i

src/flex/AST/UnitInstruction.s: src/flex/AST/UnitInstruction.cpp.s
.PHONY : src/flex/AST/UnitInstruction.s

# target to generate assembly for a file
src/flex/AST/UnitInstruction.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/UnitInstruction.cpp.s
.PHONY : src/flex/AST/UnitInstruction.cpp.s

src/flex/AST/Value.o: src/flex/AST/Value.cpp.o
.PHONY : src/flex/AST/Value.o

# target to build an object file
src/flex/AST/Value.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Value.cpp.o
.PHONY : src/flex/AST/Value.cpp.o

src/flex/AST/Value.i: src/flex/AST/Value.cpp.i
.PHONY : src/flex/AST/Value.i

# target to preprocess a source file
src/flex/AST/Value.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Value.cpp.i
.PHONY : src/flex/AST/Value.cpp.i

src/flex/AST/Value.s: src/flex/AST/Value.cpp.s
.PHONY : src/flex/AST/Value.s

# target to generate assembly for a file
src/flex/AST/Value.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/Value.cpp.s
.PHONY : src/flex/AST/Value.cpp.s

src/flex/AST/VariableDeclaration.o: src/flex/AST/VariableDeclaration.cpp.o
.PHONY : src/flex/AST/VariableDeclaration.o

# target to build an object file
src/flex/AST/VariableDeclaration.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableDeclaration.cpp.o
.PHONY : src/flex/AST/VariableDeclaration.cpp.o

src/flex/AST/VariableDeclaration.i: src/flex/AST/VariableDeclaration.cpp.i
.PHONY : src/flex/AST/VariableDeclaration.i

# target to preprocess a source file
src/flex/AST/VariableDeclaration.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableDeclaration.cpp.i
.PHONY : src/flex/AST/VariableDeclaration.cpp.i

src/flex/AST/VariableDeclaration.s: src/flex/AST/VariableDeclaration.cpp.s
.PHONY : src/flex/AST/VariableDeclaration.s

# target to generate assembly for a file
src/flex/AST/VariableDeclaration.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableDeclaration.cpp.s
.PHONY : src/flex/AST/VariableDeclaration.cpp.s

src/flex/AST/VariableScope.o: src/flex/AST/VariableScope.cpp.o
.PHONY : src/flex/AST/VariableScope.o

# target to build an object file
src/flex/AST/VariableScope.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableScope.cpp.o
.PHONY : src/flex/AST/VariableScope.cpp.o

src/flex/AST/VariableScope.i: src/flex/AST/VariableScope.cpp.i
.PHONY : src/flex/AST/VariableScope.i

# target to preprocess a source file
src/flex/AST/VariableScope.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableScope.cpp.i
.PHONY : src/flex/AST/VariableScope.cpp.i

src/flex/AST/VariableScope.s: src/flex/AST/VariableScope.cpp.s
.PHONY : src/flex/AST/VariableScope.s

# target to generate assembly for a file
src/flex/AST/VariableScope.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableScope.cpp.s
.PHONY : src/flex/AST/VariableScope.cpp.s

src/flex/AST/VariableSignature.o: src/flex/AST/VariableSignature.cpp.o
.PHONY : src/flex/AST/VariableSignature.o

# target to build an object file
src/flex/AST/VariableSignature.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableSignature.cpp.o
.PHONY : src/flex/AST/VariableSignature.cpp.o

src/flex/AST/VariableSignature.i: src/flex/AST/VariableSignature.cpp.i
.PHONY : src/flex/AST/VariableSignature.i

# target to preprocess a source file
src/flex/AST/VariableSignature.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableSignature.cpp.i
.PHONY : src/flex/AST/VariableSignature.cpp.i

src/flex/AST/VariableSignature.s: src/flex/AST/VariableSignature.cpp.s
.PHONY : src/flex/AST/VariableSignature.s

# target to generate assembly for a file
src/flex/AST/VariableSignature.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/flex/AST/VariableSignature.cpp.s
.PHONY : src/flex/AST/VariableSignature.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/pld-comp.dir/build.make CMakeFiles/pld-comp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pld-comp"
	@echo "... rebuild_cache"
	@echo "... bison.tab.o"
	@echo "... bison.tab.i"
	@echo "... bison.tab.s"
	@echo "... lex.yy.o"
	@echo "... lex.yy.i"
	@echo "... lex.yy.s"
	@echo "... src/IR/basicBlock/BasicBlock.o"
	@echo "... src/IR/basicBlock/BasicBlock.i"
	@echo "... src/IR/basicBlock/BasicBlock.s"
	@echo "... src/IR/data/AbstractData.o"
	@echo "... src/IR/data/AbstractData.i"
	@echo "... src/IR/data/AbstractData.s"
	@echo "... src/IR/data/Memory.o"
	@echo "... src/IR/data/Memory.i"
	@echo "... src/IR/data/Memory.s"
	@echo "... src/IR/data/Register.o"
	@echo "... src/IR/data/Register.i"
	@echo "... src/IR/data/Register.s"
	@echo "... src/IR/instructions/AbstractInstruction.o"
	@echo "... src/IR/instructions/AbstractInstruction.i"
	@echo "... src/IR/instructions/AbstractInstruction.s"
	@echo "... src/IR/instructions/AbstractMemoryAcess.o"
	@echo "... src/IR/instructions/AbstractMemoryAcess.i"
	@echo "... src/IR/instructions/AbstractMemoryAcess.s"
	@echo "... src/IR/instructions/AbstractOperator.o"
	@echo "... src/IR/instructions/AbstractOperator.i"
	@echo "... src/IR/instructions/AbstractOperator.s"
	@echo "... src/IR/instructions/Jump.o"
	@echo "... src/IR/instructions/Jump.i"
	@echo "... src/IR/instructions/Jump.s"
	@echo "... src/IR/instructions/Label.o"
	@echo "... src/IR/instructions/Label.i"
	@echo "... src/IR/instructions/Label.s"
	@echo "... src/IR/instructions/OperatorBigger.o"
	@echo "... src/IR/instructions/OperatorBigger.i"
	@echo "... src/IR/instructions/OperatorBigger.s"
	@echo "... src/IR/instructions/OperatorBiggerOrEqual.o"
	@echo "... src/IR/instructions/OperatorBiggerOrEqual.i"
	@echo "... src/IR/instructions/OperatorBiggerOrEqual.s"
	@echo "... src/IR/instructions/OperatorDiv.o"
	@echo "... src/IR/instructions/OperatorDiv.i"
	@echo "... src/IR/instructions/OperatorDiv.s"
	@echo "... src/IR/instructions/OperatorEquals.o"
	@echo "... src/IR/instructions/OperatorEquals.i"
	@echo "... src/IR/instructions/OperatorEquals.s"
	@echo "... src/IR/instructions/OperatorMinus.o"
	@echo "... src/IR/instructions/OperatorMinus.i"
	@echo "... src/IR/instructions/OperatorMinus.s"
	@echo "... src/IR/instructions/OperatorModulus.o"
	@echo "... src/IR/instructions/OperatorModulus.i"
	@echo "... src/IR/instructions/OperatorModulus.s"
	@echo "... src/IR/instructions/OperatorMult.o"
	@echo "... src/IR/instructions/OperatorMult.i"
	@echo "... src/IR/instructions/OperatorMult.s"
	@echo "... src/IR/instructions/OperatorPlus.o"
	@echo "... src/IR/instructions/OperatorPlus.i"
	@echo "... src/IR/instructions/OperatorPlus.s"
	@echo "... src/IR/instructions/OperatorSmaller.o"
	@echo "... src/IR/instructions/OperatorSmaller.i"
	@echo "... src/IR/instructions/OperatorSmaller.s"
	@echo "... src/IR/instructions/OperatorSmallerOrEqual.o"
	@echo "... src/IR/instructions/OperatorSmallerOrEqual.i"
	@echo "... src/IR/instructions/OperatorSmallerOrEqual.s"
	@echo "... src/IR/instructions/ReadFromMemory.o"
	@echo "... src/IR/instructions/ReadFromMemory.i"
	@echo "... src/IR/instructions/ReadFromMemory.s"
	@echo "... src/IR/instructions/WriteToMemory.o"
	@echo "... src/IR/instructions/WriteToMemory.i"
	@echo "... src/IR/instructions/WriteToMemory.s"
	@echo "... src/flex/AST/AbstractInstruction.o"
	@echo "... src/flex/AST/AbstractInstruction.i"
	@echo "... src/flex/AST/AbstractInstruction.s"
	@echo "... src/flex/AST/AbstractNode.o"
	@echo "... src/flex/AST/AbstractNode.i"
	@echo "... src/flex/AST/AbstractNode.s"
	@echo "... src/flex/AST/ArgumentList.o"
	@echo "... src/flex/AST/ArgumentList.i"
	@echo "... src/flex/AST/ArgumentList.s"
	@echo "... src/flex/AST/AssignationVariableExpression.o"
	@echo "... src/flex/AST/AssignationVariableExpression.i"
	@echo "... src/flex/AST/AssignationVariableExpression.s"
	@echo "... src/flex/AST/Block.o"
	@echo "... src/flex/AST/Block.i"
	@echo "... src/flex/AST/Block.s"
	@echo "... src/flex/AST/ComposedInstruction.o"
	@echo "... src/flex/AST/ComposedInstruction.i"
	@echo "... src/flex/AST/ComposedInstruction.s"
	@echo "... src/flex/AST/Expression/AbstractBinaryExpression.o"
	@echo "... src/flex/AST/Expression/AbstractBinaryExpression.i"
	@echo "... src/flex/AST/Expression/AbstractBinaryExpression.s"
	@echo "... src/flex/AST/Expression/AbstractExpression.o"
	@echo "... src/flex/AST/Expression/AbstractExpression.i"
	@echo "... src/flex/AST/Expression/AbstractExpression.s"
	@echo "... src/flex/AST/Expression/AddExpression.o"
	@echo "... src/flex/AST/Expression/AddExpression.i"
	@echo "... src/flex/AST/Expression/AddExpression.s"
	@echo "... src/flex/AST/Expression/Constant.o"
	@echo "... src/flex/AST/Expression/Constant.i"
	@echo "... src/flex/AST/Expression/Constant.s"
	@echo "... src/flex/AST/Expression/VariableAssignmentExpression.o"
	@echo "... src/flex/AST/Expression/VariableAssignmentExpression.i"
	@echo "... src/flex/AST/Expression/VariableAssignmentExpression.s"
	@echo "... src/flex/AST/MainBody.o"
	@echo "... src/flex/AST/MainBody.i"
	@echo "... src/flex/AST/MainBody.s"
	@echo "... src/flex/AST/MainType.o"
	@echo "... src/flex/AST/MainType.i"
	@echo "... src/flex/AST/MainType.s"
	@echo "... src/flex/AST/SequenceInstruction.o"
	@echo "... src/flex/AST/SequenceInstruction.i"
	@echo "... src/flex/AST/SequenceInstruction.s"
	@echo "... src/flex/AST/Structure/AbstractStructure.o"
	@echo "... src/flex/AST/Structure/AbstractStructure.i"
	@echo "... src/flex/AST/Structure/AbstractStructure.s"
	@echo "... src/flex/AST/Structure/ElseStructure.o"
	@echo "... src/flex/AST/Structure/ElseStructure.i"
	@echo "... src/flex/AST/Structure/ElseStructure.s"
	@echo "... src/flex/AST/Structure/IfStructure.o"
	@echo "... src/flex/AST/Structure/IfStructure.i"
	@echo "... src/flex/AST/Structure/IfStructure.s"
	@echo "... src/flex/AST/UnitInstruction.o"
	@echo "... src/flex/AST/UnitInstruction.i"
	@echo "... src/flex/AST/UnitInstruction.s"
	@echo "... src/flex/AST/Value.o"
	@echo "... src/flex/AST/Value.i"
	@echo "... src/flex/AST/Value.s"
	@echo "... src/flex/AST/VariableDeclaration.o"
	@echo "... src/flex/AST/VariableDeclaration.i"
	@echo "... src/flex/AST/VariableDeclaration.s"
	@echo "... src/flex/AST/VariableScope.o"
	@echo "... src/flex/AST/VariableScope.i"
	@echo "... src/flex/AST/VariableScope.s"
	@echo "... src/flex/AST/VariableSignature.o"
	@echo "... src/flex/AST/VariableSignature.i"
	@echo "... src/flex/AST/VariableSignature.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

